AppBundle\Entity\geners:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\genersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gName:
            type: string
            length: '20'
            column: g_name
    lifecycleCallbacks: {  }
