AppBundle\Entity\book_genre:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\book_genreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bookId:
            type: smallint
            column: book_id
        genreId:
            type: smallint
            column: genre_id
    lifecycleCallbacks: {  }
	manyToOne:
		genere:
			targetEntity: Genere
			inversedBy:book_genre
			joinColumn:
				name: gener_id
				referencedColumnName: id
		books:
			targetEntity: Books
			inversedBy:book_genre
			joinColumn:
				name: book_id
				referencedColumnName: id