AppBundle\Entity\books:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\booksRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        bookName:
            type: string
            length: '100'
            unique: true
            column: book_name
        releaseDate:
            type: date
            nullable: true
            column: release_date
        length:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
