AppBundle\Entity\book_genre:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\book_genreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
    manyToOne:
    geners:
        targetEntity: Geners
        joinColumn:
            name: gener_id
            referencedColumnName: id
    books:
        targetEntity: Books
        joinColumn:
            name: book_id
            referencedColumnName: id