AppBundle\Entity\geners:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\genersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        genre:
            type: string
            length: '50'
            unique: true
    lifecycleCallbacks: {  }
oneToMany:
book_genre:
targetEntity: Book_genre
mappedBy: geners