AppBundle\Entity\users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\usersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        family:
            type: string
            length: '100'
        username:
            type: string
            length: '100'
            unique: true
        password:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
